- name: Installing redis
  become: true
  ansible.builtin.apt:
    name: redis-server
    state: present

- name: Uploading systemd service to redis server
  become: true
  ansible.builtin.template:
    src: ../files/redis.conf
    dest: /etc/redis/redis.conf
  register: already_upload_service

- name: Stop redis server
  become: true
  ansible.builtin.systemd:
    name: redis-server
    state: stopped
    enabled: yes
  when: already_upload_service.changed

- name: Start redis server
  become: true
  ansible.builtin.systemd:
    name: redis-server
    state: started
    daemon_reload: yes
    enabled: yes