name: 'chocolatine'
run-name: ${{ github.actor }} checking if avaible to push
on:
  push:
    branches-ignore:
    - 'ga-ignore-'
  pull_request:
    branches-ignore:
    - 'ga-ignore-'

jobs:
  push_to_mirror:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:

      - name: use_checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: push_to_miror
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ vars.MIRROR_URL }}
          ssh_private_key:
            ${{ secrets.GIT_SSH_PRIVATE_KEY }}